package family.crypto.mls

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext

/**
 * The device's whole MLS state, held as one opaque snapshot (TASK-124, T010).
 *
 * The `:crypto-ffi` boundary is stateless: every verb takes the snapshot in and returns an updated
 * one ([contracts/mls-ffi-surface.md]). This class is the Kotlin side of that convention — it owns
 * the bytes, serializes access, and moves the blocking FFI call onto [Dispatchers.IO] (FR-011).
 *
 * **Deviation from plan.md §Architecture (deliberate).** The plan sketched
 * `MutableMap<GroupId, ByteArray>` — one snapshot per group. We keep ONE device-scoped snapshot
 * instead, because the openmls storage holds more than group state: signature key pairs and
 * KeyPackage bundles live there too, and a KeyPackage generated by `OpenMlsKeyPackagePort` must be
 * visible to the same storage that later joins the group its Welcome refers to. Splitting per group
 * would force us to merge snapshots on every join. Cross-group isolation is unaffected — it is
 * enforced by MLS itself (a ciphertext carries its group id), not by our map keys. TASK-125 replaces
 * the in-memory bytes with SQLCipher behind this same seam.
 *
 * **In-memory only.** State is lost on process death — that is the task's explicit scope
 * (persistence is TASK-125). No `KeyVault`, no disk, no logging of key material.
 */
internal class MlsSnapshotStore {

    private val mutex = Mutex()

    /** Serialized openmls `StorageProvider` contents. Empty = fresh device. */
    private var snapshot: ByteArray = ByteArray(0)

    /**
     * Inbound commits seen via `processMessage` but not yet merged.
     *
     * openmls' `StagedCommit` is not serializable, so it cannot live inside the snapshot. The
     * domain's two-phase contract (`processMessage` → `mergePendingCommit`) is honoured by keeping
     * the commit BYTES here and replaying them into `mlsMergeStagedCommit` on merge.
     */
    private val pendingInbound = mutableMapOf<String, ByteArray>()

    /**
     * Run [block] against the current snapshot under the store's lock, on [Dispatchers.IO].
     *
     * [block] returns the updated snapshot plus its own result; the snapshot is only committed when
     * [block] completes normally, so a failed FFI call leaves the previous state untouched.
     */
    suspend fun <T> mutate(block: (ByteArray) -> Pair<ByteArray, T>): T = mutex.withLock {
        withContext(Dispatchers.IO) {
            val (updated, result) = block(snapshot)
            snapshot = updated
            result
        }
    }

    /** Record the bytes of an inbound commit awaiting merge for [groupId]. */
    suspend fun stageInbound(groupId: String, commit: ByteArray) = mutex.withLock {
        pendingInbound[groupId] = commit
    }

    /** Take (and clear) the inbound commit staged for [groupId], if any. */
    suspend fun takeInbound(groupId: String): ByteArray? = mutex.withLock {
        pendingInbound.remove(groupId)
    }
}
