package family.push.api

import kotlinx.serialization.Serializable

/**
 * T011 — FCM data-message payload after parsing on receiver side.
 * Per spec 019 FR-024, data-model.md §PushPayload, contracts/push-payload-v1.md.
 *
 * Wire format: flat `Map<String, String>` (FCM constraint). Encoded/decoded via
 * [family.push.internal.PushPayloadWireFormat]. **Не serialized напрямую через
 * kotlinx.serialization** — нужен flat-map adapter из-за FCM ограничения.
 *
 * @Serializable аннотация — для тестовых fixtures (JSON files в commonTest/resources/).
 *
 *  • [schemaVersion] — first commit = 1. Receiver: if > MAX_SUPPORTED → silent
 *    log + ignore (FR-013 forward-compat policy).
 *  • [eventType] — string lookup в [EventType.fromWireOrNull] → if null → silent
 *    ignore (handler not registered).
 *  • [ownerUid] — Firebase UID владельца контекста (например config'а). Nullable
 *    для system events not tied to user (future SOS-broadcast variant).
 *  • [triggerId] — UUID v4 generated by client при PushTrigger.trigger(). Used as
 *    receiver debounce key (FR-044 SC-006: 10 duplicate receipts → 1 handle).
 *  • [fields] — event-type-specific payload (для config-updated: `{"configName": "main"}`).
 *    Каждое значение — String (FCM data-map constraint).
 *  • [linkId] — DEPRECATED, backward-compat for legacy spec 007/008 PushPayload
 *    с pairing model. Phase 4 migration сохраняет parsing старого поля.
 *    TODO(removal SRV-PUSH-FOUNDATION future): drop в schemaVersion 2 после
 *    8-files migration ships and pairing path rewritten.
 */
@Serializable
data class PushPayload(
    val schemaVersion: Int = WireFormatVersion.MAX_SUPPORTED_SCHEMA_VERSION,
    val eventType: String,
    val ownerUid: String? = null,
    val triggerId: String,
    val fields: Map<String, String> = emptyMap(),
    val linkId: String? = null,
)
