package com.launcher.api.link

import com.launcher.api.identity.AdminIdentity
import com.launcher.api.pairing.TrustEdgeBootstrap

/**
 * The admin↔Managed trust edge (spec 007 §Key Entities, contracts/link.md).
 * The single [TrustEdgeBootstrap] subtype in spec 007; future specs (011
 * contacts, jitsi calls, multi-admin) introduce sibling subtypes — see
 * `TrustEdgeBootstrap` kdoc.
 *
 *  - [linkId]: opaque autogenerated Firestore doc ID (OWD-4); doubles as
 *    [edgeId] for the parent interface.
 *  - [managedDeviceId]: stable UUIDv4 from DataStore (FR-001).
 *  - [managedDeviceFirebaseUid]: short-lived Firebase Auth UID; changes on
 *    reinstall if no Auto Backup (research §Identity rotation).
 *  - [createdAt]: epoch millis; server-set via FieldValue.serverTimestamp().
 *
 * TODO(spec 008): when subcollections grow beyond `state/config/capabilities/
 * health/commands`, extend [KNOWN_SUBCOLLECTIONS] so recursive-revoke
 * (FR-033) keeps deleting the full subtree.
 */
data class Link(
    val linkId: String,
    val adminId: AdminIdentity,
    val managedDeviceId: String,
    val managedDeviceFirebaseUid: String,
    override val createdAt: Long,
) : TrustEdgeBootstrap {
    override val edgeId: String get() = linkId

    companion object {
        /** Known subcollection roots under `/links/{linkId}/`. Used by
         *  `LinkRegistry.revoke()` for recursive client-side deletion
         *  (research §Recursive). Add here when a new subcollection is
         *  introduced by a future spec. */
        val KNOWN_SUBCOLLECTIONS: List<String> = listOf(
            "state",
            "config",
            "capabilities",
            "health",
            "commands",
            "configHistory",  // spec 009 FR-036 — config history snapshots.
        )
    }
}
