package family.crypto.api.values

import kotlin.jvm.JvmInline

/**
 * XChaCha20-Poly1305 envelope: `nonce(24) || ciphertext || mac(16)`.
 * Nonce is generated by the [family.crypto.api.AeadCipher] adapter internally
 * (callers MUST NOT supply or extract — see KDoc on `AeadCipher`).
 */
@JvmInline
value class Ciphertext(val bytes: ByteArray)
